# Generated by Django 4.2.2 on 2023-06-24 16:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xabar_app', '0003_commmit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commmit',
            new_name='Comment',
        ),
    ]
