# Generated by Django 4.2.2 on 2023-06-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xabar_app', '0004_rename_commmit_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
